#!/bin/bash

start()
{
    echo "start ezRegister"
    cd /home/gengs/develops/ezWork/
    /home/gengs/develops/ezWork/ezRegister.pl >> /home/gengs/ezRegister.log &
    exit 0;
}
stop()
{
     pkill ezRegister.pl
     echo "stop ezRegister"
}

case "$1" in
start)
    start
    ;;
stop)
    stop
    ;;
restart)
    stop
    start
    ;;
*)
    echo "usage: $0 start|stop|restart"
    exit 0;
esac
